2025-05-10 19:48:00,556 - JPXPipeline - INFO - Loading data...
2025-05-10 19:48:00,556 - JPXPipeline - ERROR - Pipeline failed: [Errno 2] No such file or directory: 'data\\raw\\train\\stock_prices.csv'
Traceback (most recent call last):
  File "C:\jpx_stock_prediction\src\pipeline\main_pipeline.py", line 198, in run_pipeline
    df = self.load_data()
         ^^^^^^^^^^^^^^^^
  File "C:\jpx_stock_prediction\src\pipeline\main_pipeline.py", line 68, in load_data
    stock_prices = pd.read_csv(
                   ^^^^^^^^^^^^
  File "C:\Users\BeRo074\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\BeRo074\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\BeRo074\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\BeRo074\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 1880, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "C:\Users\BeRo074\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\common.py", line 873, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'data\\raw\\train\\stock_prices.csv'
